### ISSUE TITLE
2차 오류 수정

### ISSUE THREAD

**Issue by deingvelop** [bogle-bogle/thepet-frontend#109]
## Todo list
- [x] 프론트 오류 처리 (JWT 만료, Redis)
- [x] MBTI 붙이기
- [x] 마이페이지 - 일반 주문내역 - 상품 가격 띄우기
- [x] 구독 - 1년 내역에 slider 붙이기
- [x] 마이페이지 MyInfo component -> API 만들어 붙이기

**Comment by deingvelop** [comment]
상품 가격 띄위기
