### ISSUE TITLE
3차 수정

### ISSUE THREAD

**Issue by deingvelop** [bogle-bogle/thepet-frontend#121]
## Feature Description
- 

## Todo list
- [x] 흰디카 예약 고장난 것 고치기
- [ ] 흰디카 예약 완료시 -> 예약 완료 페이지 혹은 마이페이지로 리다이렉팅
- [ ] 마이페이지 -> query string 으로 refactoring
- [ ] 일반 상품 정기배송 -> 프론트와 연결
- [x] 토큰 만료시 toast 뜨고 로그아웃
- [x] 메인으로 가서 로그인 모달 띄우도록 수정
- [x] 흰디카 이미 있는 경우 -> 프론트 예외처리
- [x] 커스텀 카드 저장
- [x] 로그아웃 제대로 구현
- [x] 로그인 안 되어있을 경우 Login 후 이용해주세요 toast 띄우기
- [ ] front 배너 만들기
