### ISSUE TITLE
front-end lighthouse

### ISSUE THREAD

**Issue by bedurgi999** [bogle-bogle/thepet-frontend#150]
## Feature Description
- 

## Todo list
- [ ] Reduce unused Javascript
- [ ] Minify Javascript
- [ ] Properly size images
- [ ] Preload Largest Contentful Paint image
- [ ] Serve images in next-gen formats
- [ ] Use HTTP/2
- [ ] Avoid enormous network payloads
- [ ] Serve static assets with an efficient cache policy
- [ ] Ensure text remains visible during webfont load
- [ ] Image elements do not have explicit width and height
- [ ] Page prevented back/forward cache restoration
- [ ] Avoid chaining critical requests
- [ ] User Timing marks and measures
- [ ] Keep request counts low and transfer sizes small
- [ ] Largest Contentful Paint element
- [ ] Avoid large layout shifts
- [ ] Avoid long main-thread tasks
